### ISSUE TITLE
User Info Fetcher: Enable TLS with WebPKI trust by default

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/opa-operator#517]
Currently, the following configuration leads to the HTTP client connecting without TLS:

```yml
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: test-opa
spec:
  clusterConfig:
    userInfo:
      backend:
        keycloak:
          hostname: keycloak.example.com
          clientCredentialsSecret: opa-infofetcher-keycloak-secret
          adminRealm: master
          userRealm: master
```

And to enable TLS, you have to jump through a few hoops by adding:

```yml
          tls:
            verification:
              server:
                caCert:
                  webPki: {}
```

In this day-in-age, I think it is expected to default to TLS (and the CRA requires secure-by-default).

So I propose that we `impl Default` for `tls`:

```rust
impl Default for TlsVerification {
    fn default() -> Self {
        Self::Server(TlsServerVerification {
            ca_cert: CaCert::WebPki {},
        })
    }
}
```

... and explicit steps are to be taken to disable TLS or to ignore verification (or set internal PKI), eg:

```yml
          tls: null 
```

or 

```yml
          tls:
            verification:
              none: {}
```
