### ISSUE TITLE
User Info Fetcher: Retrieve user info by sAMAccountName

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/opa-operator#702]
## Description

Allow the retrieval of user info by giving a sAMAccountName.

A customer handles technical and non-technical users differently in Active Directory. Technical users are e.g. created by the secret operator and have a meaningful User Principal Name, but their sAMAccountNames just consist of a prefix and a random hash. These technical users can be retrieved by `userInfoByUsername`. The non-technical users have a meaningful sAMAccountName and the UPN contains some e-mail addresses. In this case, the customer wants to retrieve the user info by sAMAccountName or preferably by a custom filter query.

## Proposed change

A field `customUserQueryFilter` is added to the CRD for the backend `experimentalActiveDirectory`. If this field is set, then the given query is used when `userInfoByUsername` is called.

`${USERNAME}` will be replaced by the requested username.

```yaml
spec:
  clusterConfig:
    userInfo:
      backend:
        experimentalActiveDirectory:
          ldapServer: ...
          baseDistinguishedName: ...
          kerberosSecretClassName: ...
          customUserQueryFilter: "(&(objectClass=person)(|(sAMAccountName=${USERNAME})(userPrincipalName=${USERNAME}))"
```

**Edits:**
- `${USER}` renamed to `${USERNAME}` and description added.
